/**
 * AUTH CALLBACK — The "landing pad" for all Supabase email links.
 *
 * This route handles BOTH email verification AND password reset links.
 * Here's what happens:
 *
 * FOR EMAIL VERIFICATION (sign-up):
 *   1. User clicks verification link in email
 *   2. Link goes to: /auth/callback?code=abc123
 *   3. We exchange the code for a session (user is now logged in + verified)
 *   4. "next" defaults to /dashboard → redirect there
 *
 * FOR PASSWORD RESET:
 *   1. User clicks reset link in email
 *   2. Link goes to: /auth/callback?code=abc123&next=/reset-password
 *   3. We exchange the code for a session (user is now logged in temporarily)
 *   4. "next" is /reset-password → redirect there so user can set new password
 *
 * The ?code parameter is a one-time-use token generated by Supabase.
 * exchangeCodeForSession() verifies it and creates a browser session.
 */
import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);

  // The one-time auth code from Supabase's email link
  const code = searchParams.get('code');

  // Where to redirect after — defaults to /dashboard for verification,
  // or /reset-password if the link came from a password reset email
  const next = searchParams.get('next') ?? '/dashboard';

  if (code) {
    const supabase = await createClient();

    // Exchange the one-time code for a real session.
    // After this, the user has cookies set and is "logged in".
    const { error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      // Success — send them where they need to go
      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // If code exchange fails (expired link, already used, etc.), send to login
  return NextResponse.redirect(`${origin}/login`);
}
